version: '3'

services:
  db:
    image: 'postgres'
  redis:
    image: redis
    expose:
      - 6379

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - API_URL=localhost:8000/api
    
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
