version: '3'

services:
  redis:
    image: redis
    expose:
      - 6379

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    
  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    links:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=${PORT}
