version: '3'

services:
  # db:
  #   image: 'postgres'
  redis:
    image: redis
    expose:
      - 6379

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    
  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend/src:/app/src
    links:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=${PORT}
